name: API Documentation

on:
  workflow_dispatch:
  push:
    tags:
      - v7.**

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@384fd19694fe7b6dcc9a684746c6976ad78228ae # v1.1.1
        id: generate-token
        with:
          creds: ${{ secrets.GH_APP_CREDS }}

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Get short SHA for HEAD
        id: get-short-sha
        run: echo "sha=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Use Node.js LTS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x
          cache: yarn

      - name: Build
        shell: bash
        run: |
          yarn
          yarn docs

      - name: Prepare docs
        uses: malept/github-action-gh-pages@f7952a65c4b763dc84b824a530dc38bd375ac91e # tag: v1.4.0
        with:
          cname: js.electronforge.io
          defaultBranch: main
          noCommit: true
          showUnderscoreFiles: true
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Commit docs
        uses: dsanders11/github-app-commit-action@48d2ff8c1a855eb15d16afa97ae12616456d7cbc # v1.4.0
        with:
          fail-on-no-changes: false
          message: 'deploy: ${{ steps.get-short-sha.outputs.sha }}'
          token: ${{ steps.generate-token.outputs.token }}
